name: sharonskitchen
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  auto_route: ^5.0.3
  carousel_slider: ^5.0.0
  responsive_sizer: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/pasta.jpg
